"""Phase 1: verify candidate citations against Crossref and build
data/metadata/literature_evidence_table.csv."""
import csv, json, time, urllib.parse, urllib.request

OUT = "data/metadata/literature_evidence_table.csv"
CACHE = "data/metadata/literature_crossref_cache.json"

# (authors, year, title-query, journal hint, study_design, unit, exposure, outcome, identification,
#  main_finding, limitation, relevance, claim_supported)
CAND = [
 ("Burnside & Dollar", 2000, "Aid, Policies, and Growth", "American Economic Review",
  "cross-country panel", "country-period", "aid/GDP", "growth", "OLS/2SLS w/ policy interaction",
  "Aid raises growth only in good policy environments", "result fragile to sample/spec",
  "anchor for aid-growth debate; motivates composition over volume", "aid effectiveness conditional"),
 ("Burnside & Dollar", 2004, "Aid, Policies, and Growth: Revisiting the Evidence",
  "World Bank Economic Review", "cross-country panel", "country-period", "aid/GDP", "growth",
  "robustness of BD2000", "policy interaction not robust", "confirms fragility of aid-growth link",
  "motivates architecture not volume", "fragility of aid-growth"),
 ("Easterly", 2003, "Can Foreign Aid Buy Growth?", "Journal of Economic Perspectives",
  "reanalysis", "country-period", "aid", "growth", "replication + new data",
  "no robust aid-growth effect even in good policy", "aggregate correlation limits",
  "motivates looking beyond aggregate volume", "no robust aggregate effect"),
 ("Clemens et al.", 2012, "Counting Chickens When They Hatch: Timing and the Effects of Aid on Growth",
  "Economic Journal", "cross-country panel", "country-4yr", "early-impact aid", "growth",
  "lag-timing correction", "positive effect of early-impact aid", "instrument criticism persists",
  "supports lag-structure focus", "timing matters"),
 ("Rajan & Subramanian", 2008, "Aid and Growth: What Does the Cross-Country Evidence Really Show?",
  "Review of Economics and Statistics", "cross-country panel", "country-decade", "aid/GDP", "growth",
  "external instrument (supply-side)", "no aid-growth relationship", "IV validity debated",
  "benchmark null; justifies architecture decomposition", "aggregate null"),
 ("Doucouliagos & Paldam", 2009, "The Aid Effectiveness Literature: The Sad Results of 40 Years of Research",
  "Journal of Economic Surveys", "meta-analysis", "study", "aid coefficients", "growth",
  "meta-regression", "average effect ~zero; publication bias", "heterogeneity of designs",
  "justifies need for new estimand", "meta-null"),
 ("Boone", 1996, "Politics and the Effectiveness of Foreign Aid", "European Economic Review",
  "cross-country", "country", "aid", "consumption/investment", "reduced form",
  "aid funds consumption not investment", "dated data", "baseline 'aid fails to invest' claim",
  "aid-fungibility concern"),
 ("Feyzioglu, Swaroop & Zhu", 1998, "A Panel Data Analysis of the Fungibility of Foreign Aid",
  "World Bank Economic Review", "panel", "country-year", "sector aid", "public spending",
  "panel regression", "aid fungible across sectors", "identification weak",
  "motivates modality composition", "fungibility"),
 ("Devarajan & Swaroop", 1998, "The Implications of Foreign Aid Fungibility for Development Assistance",
  "World Bank policy working paper", "conceptual+empirical", "country", "aid", "public accounts",
  "fungibility framework", "earmarking may be illusory", "WP not peer-reviewed",
  "fungibility theory", "fungibility caveat"),
 ("Wagner", 2014, "Aid and the Dutch Disease: Macroeconomic Management When Everybody Loves You",
  "OECD Development Centre Working Paper", "DSGE/simulation", "country", "aid surge", "real exchange rate",
  "model simulation", "aid can appreciate real exchange rate", "model-based",
  "Dutch disease mechanism for architecture", "macro side-channel"),
 ("Rajan & Subramanian", 2011, "Aid, Dutch Disease, and Manufacturing Growth",
  "Journal of Development Economics", "cross-country industry", "country-industry", "aid",
  "manufacturing growth", "diff-in-diff across industries",
  "aid slows tradable sector growth", "industry identification assumptions",
  "links composition to tradables", "Dutch disease evidence"),
 ("Knack", 2001, "Aid Dependence and the Quality of Governance: Cross-Country Empirical Tests",
  "Southern Economic Journal", "cross-country", "country", "aid dependence", "governance",
  "OLS/IV", "aid dependence erodes governance", "IV debated",
  "capacity-formation outcome justification", "aid-dependence harms institutions"),
 ("Brautigam & Knack", 2004, "Foreign Aid, Institutions, and Governance in Sub-Saharan Africa",
  "Economic Development and Cultural Change", "panel", "country-year", "aid", "governance/tax",
  "panel FE", "high aid linked to weaker institutions and lower tax effort", "measurement limits",
  "fiscal-capacity outcome", "aid-institutions channel"),
 ("Annen & Kosek", 2016, "Aid and Growth in the Least Developed Countries",
  "IMF Working Paper", "panel", "country", "aid", "growth", "GMM",
  "fragmentation reduces returns to aid", "working paper",
  "architecture/fragmentation link", "fragmentation cost"),
 ("Alesina & Dollar", 2000, "Who Gives Foreign Aid to Whom and Why?", "Journal of Economic Growth",
  "cross-country dyadic", "donor-recipient", "aid allocation", "aid received", "allocation regression",
  "donor strategic motives drive allocation", "allocation not outcomes",
  "donor heterogeneity baseline", "allocation endogeneity"),
 ("Kilby & Dreher", 2010, "The Impact of Aid on Growth Revisited: Do Donor Motives Matter?",
  "Economics Letters", "panel", "country", "aid by motive", "growth", "motive-decomposition",
  "politically-motivated aid less growth-effective", "motive measurement",
  "donor motives enter architecture", "motive heterogeneity"),
 ("Dreher, Nunnenkamp & Thiele", 2008, "Does Aid for Education Educate Children? Evidence from Panel Data",
  "World Bank Economic Review", "panel", "country", "education aid", "enrollment",
  "sectoral aid-outcome link", "sector aid modestly raises enrollment", "sector outcomes limited",
  "sector-portfolio precedent", "sectoral heterogeneity"),
 ("Dreher, Fuchs & Nunnenkamp", 2013, "New Kids on the Block? The Impact of Emerging Donors on Aid Delivery",
  "World Development", "cross-country", "recipient", "emerging-donor aid", "institutions",
  "descriptive+regression", "non-DAC donors differ in delivery", "scope limited",
  "donor heterogeneity beyond DAC", "emerging donors differ"),
 ("Nowak-Lehmann et al.", 2012, "Does Aid Really Help? Donor Herding Versus Donor Selectivity",
  "Oxford Development Studies", "panel", "donor-recipient", "aid", "growth", "dyadic panel",
  "donor coordination/herding matters", "identification weak",
  "dyadic design precedent", "donor-recipient interactions"),
 ("Arndt, Jones & Tarp", 2015, "Assessing Foreign Aid's Long-Run Contribution to Growth and Development",
  "World Development", "panel", "country", "aid", "growth/poverty", "long-run panel",
  "modest positive long-run aid effect", "long-run identification hard",
  "persistent-outcome framing", "long-run effects possible"),
 ("Galiani et al.", 2017, "The Effect of Aid on Growth: Evidence from a Quasi-Experiment",
  "Journal of Economic Growth", "quasi-experiment", "country", "IDA eligibility threshold", "growth",
  "fuzzy RDD on IDA threshold", "positive effect near eligibility cutoff", "local estimate",
  "identification precedent (threshold RDD)", "quasi-causal template"),
 ("Easterly & Pfutze", 2008, "Where Does the Money Go? Best and Worst Practices in Foreign Aid",
  "Journal of Economic Perspectives", "agency descriptive", "aid agency", "agency aid practices",
  "transparency/specialization scores", "best-practice ranking",
  "donor practices differ widely", "practice indices not outcomes",
  "donor-practice heterogeneity", "donor practices differ"),
 ("Dreher et al.", 2022, "Is Favoritism a Threat to Chinese Aid Effectiveness? A Subnational Analysis",
  "Journal of Development Economics", "subnational", "region", "Chinese aid", "nightlights growth",
  "subnational diff", "leader-birthplace targeting; aid boosts growth", "single donor",
  "aid within-country allocation", "targeting distortions"),
 ("Morrissey", 2001, "Does Aid Increase Growth?", "Progress in Development Studies", "review",
  "literature", "aid", "growth", "narrative review", "channels: investment, policy, Dutch disease",
  "pre-2001", "channel taxonomy for levels", "channels framework"),
 ("Bourguignon & Sundberg", 2007, "Aid Effectiveness: Opening the Black Box", "American Economic Review P&P",
  "conceptual", "na", "aid chain", "outcomes", "theory of aid delivery chain",
  "aid impact runs through delivery chain", "no empirics", "conceptual chain anchor",
  "delivery chain decomposition"),
 ("Minoiu & Reddy", 2010, "Development Aid and Economic Growth: A Positive Long-Run Relation",
  "Quarterly Review of Economics and Finance", "panel", "country", "aid", "growth", "panel cointegration",
  "positive long-run aid-growth relation", "cointegration assumptions",
  "long-run specification", "long-run positive"),
 ("Temple", 2010, "Aid and Conditionality", "Handbook of Development Economics", "handbook chapter",
  "na", "aid", "growth", "survey", "aid-conditionality record poor", "survey",
  "modality (conditionality) literature", "modality matters"),
 ("Clay, Geddes & Natali", 2009, "Untying Aid: Is It Working?", "DIIS report",
  "policy evaluation", "donor", "tying status", "procurement cost", "descriptive+interviews",
  "untied aid not equivalent to local procurement", "donor self-report",
  "tying vs local supplier distinction", "untied != local"),
 ("Jepma", 1991, "The Tying of Aid", "OECD publication", "policy analysis", "donor", "tied aid",
  "cost", "cost-comparison", "tying raises costs 10-30%", "dated",
  "tied-aid cost anchor", "tying distortion"),
 ("Morrissey & White", 1996, "Evaluating the Concessionality of Tied Aid", "Manchester School",
  "conceptual+empirical", "loan", "tying", "grant element", "grant-element accounting",
  "tying erodes concessionality", "dated", "finance-type interaction", "tying-grant link"),
 ("Dreher & Fuchs", 2015, "Rogue Aid? An Empirical Analysis of China's Aid Allocation",
  "Canadian Journal of Economics", "cross-country", "recipient", "Chinese aid", "allocation",
  "allocation regression", "China aid follows own commercial/geopolitical interests",
  "China-only", "donor motive variation", "motive heterogeneity"),
 ("Fuchs & Vadlamannati", 2013, "The Needy Donor: An Empirical Analysis of India's Aid Motives",
  "World Development", "cross-country", "recipient", "Indian aid", "allocation", "allocation regression",
  "India aid driven by politics/economics", "India-only", "non-DAC heterogeneity", "motive variation"),
 ("Doucouliagos & Paldam", 2011, "The Ineffectiveness of Development Aid on Growth: An Update",
  "European Journal of Political Economy", "meta-analysis", "study", "aid coefficients", "growth",
  "meta-regression update", "effect remains ~zero on average", "heterogeneity across studies",
  "reinforces need for architecture", "meta-null update"),
 ("Mekasha & Tarp", 2013, "Aid and Growth: What Meta-Analysis Reveals", "Journal of Development Studies",
  "meta-analysis", "study", "aid coefficients", "growth", "meta-regression",
  "genuine positive but small effect; strong publication bias", "meta limits",
  "small positive mean effect", "meta-positive small"),
 ("Herbst", 2000, "States and Power in Africa", "Princeton UP", "book", "na", "na", "na",
  "historical analysis", "aid to weak states props up institutions", "non-econometric",
  "institutional context", "context moderation"),
 ("Nowak-Lehmann, Martinez-Zarzoso & Herzer", 2009, "Aid and the Donor Countries' Exports",
  "Comparative Economic Studies", "panel", "dyad", "aid", "donor exports", "gravity/panel",
  "aid raises donor exports (tying benefit)", "mechanism not outcome",
  "tying→donor-supplier link", "tying rationale"),
 ("Pettersson", 2007, "Foreign Sectoral Aid Fungibility, Growth and Poverty Reduction",
  "Journal of International Development", "panel", "country", "sector aid", "growth/poverty",
  "sector aid regression", "sector composition matters for poverty", "identification limits",
  "sector composition outcome link", "composition matters"),
 ("Biscaye, Reynolds & Anderson", 2017, "Relative Effectiveness of Bilateral and Multilateral Aid",
  "Journal of Development Effectiveness", "review/meta", "study", "bi vs multi aid", "outcomes",
  "systematic review", "no consistent bi-vs-multi superiority", "evidence thin",
  "channel heterogeneity", "channel comparison"),
 ("Bulir & Hamann", 2008, "Volatility of Development Aid: From the Frying Pan into the Fire?",
  "World Development", "panel", "country", "aid volatility", "growth", "volatility regression",
  "aid volatility worsens with time", "volatility not architecture",
  "exposure stability consideration", "volatility channel"),
 ("Desai & Kharas", 2010, "The California Consensus: Can Private Aid End Global Poverty?",
  " Brookings", "essay", "na", "private aid", "poverty", "analysis",
  "private/NGO channels differ", "non-technical", "channel heterogeneity", "channel motives"),
 ("Feeny & McGillivray", 2008, "What Determines Bilateral Aid Allocations? Evidence Across Time",
  "Review of International Economics", "panel", "donor-recipient", "aid allocation", "bilateral aid",
  "dyadic allocation", "recipient need vs donor interest both matter", "allocation not outcome",
  "dyadic endogeneity", "allocation determinants"),
 ("Berthelemy & Tichit", 2004, "Bilateral Donors' Aid Allocation Decisions: A Three-Dimensional Panel Analysis",
  "International Review of Economics & Finance", "3d panel", "donor-recipient-year", "aid",
  "allocation", "3-way FE", "donor and recipient effects sizable", "allocation focus",
  "dyadic FE precedent", "dyadic FE design"),
 ("Greenhill, Priolo & Ward", 2013, "Donor-Recipient Dyadic Ties and Aid Allocation",
  "Political Studies", "dyadic", "dyad", "ties", "aid", "network analysis",
  "dyadic ties predict aid", "allocation only", "dyadic design", "dyadic structure"),
 ("Gehring et al.", 2017, "AidData 3.0: A Comprehensive Dataset of Global Development Finance",
  "AidData working paper", "data description", "project", "aid flows", "na", "dataset",
  "geocoded global development finance", "non-DAC measurement issues",
  "validation source", "Alt data source"),
 ("Tinbergen", 1967, "Economic Policy: Principles and Design", "North-Holland", "theory", "na",
  "instruments", "targets", "policy theory", "targets need instruments",
  "general framing only", "counterfactual framing", "portfolio logic"),
 ("Mosley", 1987, "Overseas Aid: Its Defence and Reform", "Wheatsheaf", "book", "na",
  "aid", "development", "analysis", "aid critique framework", "dated",
  "historical framing", "aid critique"),
 ("Herkenrath", 2014, "Technical Cooperation and the Reproduction of Global Inequality",
  "Cambridge Review of International Affairs", "conceptual", "na", "technical cooperation", "capacity",
  "critical analysis", "TC may reproduce dependence", "normative",
  "TC mechanism caution", "TC skepticism"),
 ("Fukuda-Parr, Lopes & Malik", 2002, "Capacity for Development: New Solutions to Old Problems",
  "UNDP/Earthscan", "policy volume", "na", "capacity building", "development", "framework",
  "capacity development redefinition", "non-econometric", "capacity concept anchor",
  "capacity definition"),
 ("Browne", 2006, "Aid and Influence: Do Donors Help or Hinder?", "Earthscan", "policy analysis",
  "na", "aid", "institutions", "analysis", "aid can undermine recipient institutions",
  "non-econometric", "institutional mechanism", "institutional channel"),
 ("Kenny", 2008, "What Is Effective Aid? How Would Donors Allocate It?",
  "European Journal of Development Research", "analysis", "donor", "aid", "effectiveness",
  "counterfactual allocation", "donor allocations differ from effective benchmarks",
  "normative benchmark", "counterfactual portfolio logic", "reallocation framing"),
]

rows, cache = [], {}
for (authors, year, qtitle, journal, design, unit, exposure, outcome, ident, finding, lim, rel, claim) in CAND:
    q = urllib.parse.quote(qtitle)
    url = f"https://api.crossref.org/works?query.bibliographic={q}&rows=3"
    verified, doi, jtitle, jyear, jjournal = "no", "", qtitle, year, journal
    try:
        with urllib.request.urlopen(url, timeout=30) as r:
            items = json.load(r)["message"]["items"]
        if items:
            top = items[0]
            doi = top.get("DOI", "")
            jtitle = (top.get("title") or [qtitle])[0]
            jjournal = (top.get("container-title") or [journal])[0]
            ys = top.get("issued", {}).get("date-parts", [[None]])[0][0]
            jyear = ys or year
            verified = "crossref"
    except Exception as e:
        verified = f"error:{type(e).__name__}"
    cache[qtitle] = {"doi": doi, "title": jtitle, "journal": jjournal, "year": jyear}
    rows.append({
        "citation_id": f"L{len(rows)+1:02d}",
        "authors": authors, "year": year, "title": jtitle, "journal": jjournal, "doi": doi,
        "study_design": design, "dataset": "", "unit_of_analysis": unit, "exposure": exposure,
        "outcome": outcome, "identification": ident, "main_finding": finding,
        "limitation": lim, "relevance_to_current_study": rel, "claim_supported": claim,
        "verified": verified,
    })
    print(f"{len(rows):02d} {authors} {year} -> {verified} {doi}")
    time.sleep(0.5)

with open(OUT, "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader(); w.writerows(rows)
json.dump(cache, open(CACHE, "w"), indent=1)
print(f"wrote {OUT} ({len(rows)} rows)")
